# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qrocodile < Formula
  desc "Generate styled QR codes (SVG or PNG) from a terminal, script, or CI pipeline — the QRocodile CLI."
  homepage "https://qrocodile.io"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/qrocodile-io/qrocodile-cli/releases/download/v0.1.0/qrocodile_0.1.0_darwin_amd64.tar.gz"
      sha256 "f127ff93002dfc2de61858536306d08cd73f0a4ddad0580bd22bc5f85ba7e9ec"

      define_method(:install) do
        bin.install "qrocodile"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/qrocodile-io/qrocodile-cli/releases/download/v0.1.0/qrocodile_0.1.0_darwin_arm64.tar.gz"
      sha256 "00b573db5445b03cce09a1d52c0f4f113f240b1772c54621348aef8333fda41c"

      define_method(:install) do
        bin.install "qrocodile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/qrocodile-io/qrocodile-cli/releases/download/v0.1.0/qrocodile_0.1.0_linux_amd64.tar.gz"
      sha256 "2ca698479a89d7da6915e59f7ca8090f8344a6cdf57b22eaf394573bd660964a"
      define_method(:install) do
        bin.install "qrocodile"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/qrocodile-io/qrocodile-cli/releases/download/v0.1.0/qrocodile_0.1.0_linux_arm64.tar.gz"
      sha256 "2b6b9420ba96557fa9ccccff7f78a39f006d62b80ee7227e0b42ebe5d782beb1"
      define_method(:install) do
        bin.install "qrocodile"
      end
    end
  end

  test do
    system "#{bin}/qrocodile", "version"
  end
end
